### ISSUE TITLE
could you please share the dataset？

### ISSUE THREAD

**Issue by PeifengRen** [Deepa-Tilwani/Spring-School-BCI-hackathon-2021#1]
I missed Spring School 2021 and didn't know where to get the dataset. Thank you so much.

**Comment by Deepa-Tilwani** [comment]
I am not sure if they allow putting data public. I can't.

**Comment by PeifengRen** [comment]
That's unfortunate. Thank you all the same. I have the data for 2020, I don't know whether it is the same as 2021?

**Comment by Deepa-Tilwani** [comment]
Sorry. I did not participate in 2020. I can't tell
